config/routes.rb
Rails.application.routes.draw do
    get 'welcome/index'
    get 'property', to: "property#index"

    root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/property_controller.rb
class PropertyController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperPortal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Arimo:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/property/_property-description.html.erb
<div class="l-property__description">
  <div>
    <b>
      Descripción
    </b>
  </div>
  <div>
    Donec hendrerit malesuada mauris. Fusce at dolor nec erat convallis efficitur
    finibus eu eros. Sed erat ligula, commodo vel feugiat ac, pellentesque at
    ante. Vivamus diam massa, lacinia at arcu sed, sollicitudin cursus erat. Etiam
    lectus erat, blandit at scelerisque vitae, semper et odio. Vivamus vitae metus
    tincidunt, lacinia urna quis, vehicula ipsum. Cras ac neque ac nulla cursus
    finibus vitae in tortor. Sed tempus arcu orci, et feugiat nibh lobortis at. In
    hac habitasse platea dictumst. Vivamus viverra nisi non mi elementum, a
    aliquet lectus vehicula. Donec a risus ac urna molestie pellentesque. Integer
    ultricies purus et quam finibus volutpat.
  </div>
  <div>
    <b>
      Características
    </b>
  </div>
  <div class="l-property__list">
    <i class="fas fa-check"></i> Accesible para Personas con Capacidades Diferentes
    <br />
    <i class="fas fa-check"></i> Aire Acondicionado
    <br />
    <i class="fas fa-check"></i> Alarma de Seguridad
    <br />
    <i class="fas fa-check"></i> Balcón
    <br />
    <i class="fas fa-check"></i> Calentador de Agua
    <br />
    <i class="fas fa-check"></i> Chiminea
    <br />
    <i class="fas fa-check"></i> Portero
    <br />
    <i class="fas fa-check"></i> Seguridad Privada
  </div>
</div>

app/views/property/_property-details.html.erb
<div class="l-property__details">
  <div class="property-detail">
    <p class="property-detail__title title title--white">
      $5,000
    </p>
    <p class="property-detail__label">
      En venta
    </p>
  </div>
  <div class="property-detail">
    <p class="property-detail__title title title--white">
      $5,000
    </p>
    <p class="property-detail__label">
      En venta
    </p>
  </div>
  <div class="property-detail">
    <p class="property-detail__title title title--white">
      3
    </p>
    <p class="property-detail__label">
      Recamaras
    </p>
  </div>
  <div class="property-detail">
    <p class="property-detail__title title title--white">
      2
    </p>
    <p class="property-detail__label">
      Baños
    </p>
  </div>
  <div class="property-detail">
    <p class="property-detail__title title title--white">
      400 sq. ft.
    </p>
    <p class="property-detail__label">
      En venta
    </p>
  </div>
  <div class="property-detail">
    <p class="property-detail__title title title--white">
      400 sq. ft.
    </p>
    <p class="property-detail__label">
      En venta
    </p>
  </div>
  <div class="property-detail">
    <p class="property-detail__title title title--white">
      300 sq. ft.
    </p>
    <p class="property-detail__label">
      Terreno
    </p>
  </div>
  <div class="property-detail">
    <p class="property-detail__title title title--white">
      2
    </p>
    <p class="property-detail__label">
      Estacionamientos
    </p>
  </div>
</div>

app/views/property/_property-form.html.erb
<div class="l-property__contact property-form">
  <img class="property-form__image" src="http://lorempixel.com/200/200/people/" />
  <p class="property-form__name">Olivia Fonseca</p>
  <p class="property-form__phone"><i class="fas fa-xs fa-phone-alt"></i> 55-1660-7461</p>
  <form>
    <input class="input input--full-width" placeholder="Tu nombre" />
    <input class="input input--full-width" placeholder="Tu e-mail" />
    <textarea class="input input--full-width" placeholder="Tu mensaje" /></textarea>
    <button class="button button--black button--full-width">
      Enviar mensaje
    </button>
  </form>
</div>

app/views/property/_property-map.html.erb
<div class="l-property__map position-relative">
  <div class="direction-box">
    <i class="fas fa-white fa-map-marker-alt fa-outline"></i>
    Sevilla 113, Portales Norte, Benito Juáres, Distrito Federal
  </div>
  <iframe
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30099.766589818668!2d-99.15047806257512!3d19.43525714563266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1f932eba629cf%3A0xa042febddcff95a!2sCentro%20Cultural%20Espa%C3%B1a%20en%20M%C3%A9xico!5e0!3m2!1ses-419!2smx!4v1577741112807!5m2!1ses-419!2smx"
    width="100%"
    height="400"
    frameborder="0"
    style="border:0;"
    allowfullscreen=""></iframe>
</div>

app/views/property/_property-related.html.erb
<div class="l-property__related related-properties">
  <div class="container">
    <h3 class="related-properties__title title">
      Propiedades Similares
    </h3>
    <div class="related-properties__listing">
      <%= render "shared/house-card",
        image: "listing-1.jpg",
        operation: "Venta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
      <%= render "shared/house-card",
        image: "listing-2.jpg",
        operation: "Venta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
      <%= render "shared/house-card",
        image: "listing-3.jpg",
        operation: "Venta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
    </div>
  </div>
</div>

app/views/property/index.html.erb
<div class="l-property">
  <div class="l-property__header">
    <div class="l-property__direction">
      <div class="container">
        <i class="fas fa-map-marker-alt fa-outline"></i>
        Sevilla 113, Portales Norte, Benito Juáres, Distrito Federal
        <h1 class="title">
          Departamento amplio y remodelado en Portales Norte
        </h1>
      </div>
    </div>
    <div class="l-property__photos owl-carousel owl-theme property-carousel">
      <%= image_tag("property-1.png") %>
      <%= image_tag("property-2.jpg") %>
      <%= image_tag("property-3.jpg") %>
    </div>
    <div class="l-property__info">
      <div class="container">
        <div class="relative-position">
          <%= render "property-details" %>
          <%= render "property-form" %>
        </div>
      </div>
    </div>
  </div>
  <div class="l-property__content">
    <div class="container">
      <%= render "property-description" %>
      <%= render "property-map" %>
      <%= render "property-related" %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $(".owl-carousel").owlCarousel({
      loop: true,
      nav: true,
      dots: true,
      items: 1,
      navText: ['<i class="fas fa-chevron-left"></i>','<i class="fas fa-chevron-right"></i>']
    });
  });
</script>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="footer__content">
      <div>
        <p class="footer__title title title--white">
          Contáctanos
        </p>
        <p>
          Av. Insurgentes Sur 0000, 4o piso
          <br />
          Col. Condesa, 00000, Ciudad de México
          <br />
          Teléfono: 505050505
          <br />
          daniel@easybroker.com
        </p>
      </div>
      <div>
        <p class="footer__title title title--white">
          Menú
        </p>
        <ul>
          <%= link_to("#") do %>
            <li class="footer__link">Inicio</li>
          <% end %>
          <%= link_to("#") do %>
            <li class="footer__link">Ventas</li>
          <% end %>
          <%= link_to("#") do %>
            <li class="footer__link">Rentas</li>
          <% end %>
          <%= link_to("#") do %>
            <li class="footer__link">Contáctanos</li>
          <% end %>
          <%= link_to("#") do %>
            <li class="footer__link">Propietarios</li>
          <% end %>
          <%= link_to("#") do %>
            <li class="footer__link">¿Quienes Sómos?</li>
          <% end %>
        </ul>
      </div>
      <div>
        <p class="footer__title title title--white">
          Contáctanos
        </p>
        <p>
          Av. Insurgentes Sur 0000, 4o piso
          <br />
          Col. Condesa, 00000, Ciudad de México
          <br />
          Teléfono: 505050505
          <br />
          daniel@easybroker.com
        </p>
      </div>
    </div>
    <hr />
    <div class="footer__powered">
      Powered by EasyBroker
    </div>
    <hr />
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="container">
    <div class="header__information">
      <div class="header__logo">
        <span class="header__brand title">Praga</span>
        <br />
        <span class="header__slogan">Real state company</span>
      </div>
      <div class="header__contact">
        <span class="header__cta">
          LLamanos
        </span>
        <br />
        <div>
          <b>
            55 1660 7461
          </b>
        </div>
      </div>
      <div class="header__social_media">
        <span class="fa-stack">
          <i class="far fa-circle fa-stack-2x"></i>
          <i class="fab fa-facebook-f fa-stack-1x"></i>
        </span>
        <span class="fa-stack">
          <i class="far fa-circle fa-stack-2x"></i>
          <i class="fab fa-twitter fa-stack-1x"></i>
        </span>
        <span class="fa-stack">
          <i class="far fa-circle fa-stack-2x"></i>
          <i class="fab fa-linkedin-in fa-stack-1x"></i>
        </span>
        <span class="fa-stack">
          <i class="far fa-circle fa-stack-2x"></i>
          <i class="fab fa-youtube fa-stack-1x"></i>
        </span>
        <span class="fa-stack">
          <i class="far fa-circle fa-stack-2x"></i>
          <i class="fab fa-instagram fa-stack-1x"></i>
        </span>
        <span class="fa-stack">
          <i class="far fa-circle fa-stack-2x"></i>
          <i class="fab fa-pinterest fa-stack-1x"></i>
        </span>
        <span class="fa-stack">
          <i class="far fa-circle fa-stack-2x"></i>
          <i class="fab fa-whatsapp fa-stack-1x"></i>
        </span>
      </div>
      <div class="header__search">
        <div class="header__search-box">
          <i class="fas fa-search fa-sm"></i>
          <input class="input" placeholder="Buscar propiedades">
        </div>
      </div>
    </div>
    <nav class="header__navigation">
      <ul class="header__menu">
        <%= link_to("#") do %>
          <li class="header__link header__link--active">Inicio</li>
        <% end %>
        <%= link_to("#") do %>
          <li class="header__link">Ventas</li>
        <% end %>
        <%= link_to("#") do %>
          <li class="header__link">Rentas</li>
        <% end %>
        <%= link_to("#") do %>
          <li class="header__link">Contáctanos</li>
        <% end %>
        <%= link_to("#") do %>
          <li class="header__link">Propiertarios</li>
        <% end %>
        <%= link_to("#") do %>
          <li class="header__link">¿Quienes Sómos?</li>
        <% end %>
      </ul>
      <nav>
  </div>
</header>

app/views/shared/_house-card.html.erb
<div class="house-card">
  <%= link_to property_path do %>
    <div class="house-card__ad">
      <div class="house-card__contract">
        <%= operation %>
      </div>
      <div class="house-card__price">
        $<%= price %>
      </div>
      <%= image_tag(image, class: "house-card__image") %>
    </div>
    <p class="house-card__description">
      <%= description %>
    </p>
  <% end %>
  <div>
    <span class="house-card__item">
      <i class="fas fa-bed fa-outline"></i> <%= beds %>
    </span>
    <span class="house-card__item">
      <i class="fas fa-bath fa-outline"></i> <%= baths %>
    </span>
    <span class="house-card__item">
      <i class="fas fa-car fa-outline"></i> <%= parking %>
    </span>
    <span class="house-card__item">
      <i class="fas fa-arrows-alt fa-outline"></i> <%= space %> sq. ft.
    </span>
  </div>
</div>

app/views/welcome/_agent-card.html.erb
<div class="agent-card">
  <img class="agent-card__image" src=<%= image %> />
  <div class="agent-card__information">
    <span class="agent-card__name"><%= name %></span>
    <br />
    <span><i class="fas fa-xs fa-phone-alt"></i> <%= phone %></span>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="hero-image">
  <div class="container">
    <div class="landing-form">
      <h1 class="landing-form__title title">
        Encuentra tu
        <br />
        próxima casa
      </h1>
      <form>
        <div class="select select--full-width">
          <select>
            <option value="venta">Propiedades en Venta</option>
            <option value="renta">Propiedades en Renta</option>
            <select>
        </div>
        <br />
        <div class="select select--full-width">
          <select>
            <option value="">Tipo de propiedad</option>
            <option value="departamento">Departamento</option>
          </select>
        </div>
        <br />
        <button class="button button--full-width">
          Buscar propiedades
        </button>
      </form>
    </div>
  </div>
</div>
<div class="l-welcome">
  <div class="container">
    <h2 class="l-welcome__title title">
      Propiedades Destacadas
    </h2>
    <div class="l-welcome__properties">
      <%= render "shared/house-card",
        image: "listing-1.jpg",
        operation: "Venta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
      <%= render "shared/house-card",
        image: "listing-2.jpg",
        operation: "Renta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
      <%= render "shared/house-card",
        image: "listing-3.jpg",
        operation: "Venta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
      <%= render "shared/house-card",
        image: "listing-4.jpg",
        operation: "Venta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
      <%= render "shared/house-card",
        image: "listing-5.jpg",
        operation: "Venta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
      <%= render "shared/house-card",
        image: "listing-6.jpg",
        operation: "Venta",
        price: "3,200,000",
        description: "Casa en Hipódromo Condesa, Cuauhtémoc",
        beds: 3,
        baths: 2,
        parking: 2,
        space: 300
      %>
    </div>
    <h2 class="l-welcome__title title">Nuestros Agentes Destacados</h2>
    <div class="l-welcome__agents">
      <div class="owl-carousel">
        <%= render "agent-card",
          image: "http://lorempixel.com/200/300/people/1/",
          name: "Scott Pilgrim",
          phone: "(555) 555-5555"
        %>
        <%= render "agent-card",
          image: "http://lorempixel.com/200/300/people/2/",
          name: "Rihanna Fenty",
          phone: "(555) 555-5555"
        %>
        <%= render "agent-card",
          image: "http://lorempixel.com/200/300/people/3/",
          name: "Melvin Gordon",
          phone: "(555) 555-5555"
        %>
        <%= render "agent-card",
          image: "http://lorempixel.com/200/300/people/4/",
          name: "Mariah Carey",
          phone: "(555) 555-5555"
        %>
        <%= render "agent-card",
          image: "http://lorempixel.com/200/300/people/5/",
          name: "Peter Parker",
          phone: "(555) 555-5555"
        %>
        <%= render "agent-card",
          image: "http://lorempixel.com/200/300/people/6/",
          name: "John Adams",
          phone: "(555) 555-5555"
        %>
        <%= render "agent-card",
          image: "http://lorempixel.com/200/300/people/7/",
          name: "John Adams",
          phone: "(555) 555-5555"
        %>
        <%= render "agent-card",
          image: "http://lorempixel.com/200/300/people/8/",
          name: "John Adams",
          phone: "(555) 555-5555"
        %>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
    loop: false,
    margin: 30,
    nav: true,
    center: true,
    dots: false,
    autoWidth: true,
    responsive: {
      0: {
        items: 1
      },
      400: {
        items: 2
      },
      600: {
        items: 3
      },
      1000: {
        items: 4
      }
    },
    navText: ['←','→']
  });
});
</script>